version: '3'

services:
  web:
    image: darwingrant04/crudphp
    container_name: php
    links:
      - "db:cldadmifinals_default"
    depends_on:
      - db
    volumes:
      - ./var/www/html/
    ports:
       - "8000:80"
    stdin_open: true
    tty: true

  db:
    image: darwingrant04/cruddb
    container_name: db
    ports:
      - "3306:3306"
